Repository alight659/ClipBin, pull requests merged in 2025-10, with the labels that each got.

#21 Added ci workflow
  .github/workflows/ci.yml
Labels: hacktoberfest, hacktoberfest-accepted

#23 Added GitHub Issue And Pull Request Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 Feat/add tests
  Makefile
  README.md
  app.py
  pyproject.toml
  requirements.txt
  sqlite.py
  test_minimal.py
  tests/__init__.py
  tests/conftest.py
  tests/test_additional.py
  tests/test_app.py
  tests/test_basic_app.py
  tests/test_database_cleanup.py
  tests/test_helpers.py
  tests/test_integration.py
  tests/test_sqlite.py
Labels: hacktoberfest, hacktoberfest-accepted

#39 Comprehensive README Update For Better Usability
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#52 fix: Decrypt content for password-protected downloads
  app.py
Labels: hacktoberfest, hacktoberfest-accepted

#68 Modev1
  static/style.css
  templates/layout.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#64 Added copy-to-clipboard button
  templates/clip.html
Labels: hacktoberfest, hacktoberfest-accepted

#63 feat(auth): make safari autofill work
  templates/login.html
  templates/register.html
Labels: hacktoberfest, hacktoberfest-accepted
